name: Fetch Composite Secret from AWS Secrets Manager

on: [push]

jobs:
  fetch-secret1:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::577638356286:role/compositegit
        aws-region: us-east-1

    - name: Fetch secret from AWS Secrets Manager
      id: fetch-secret
      uses: aws-actions/aws-secrets-manager-action@v1
      with:
        secret-id: comp-secret
        region: us-east-1

    - name: Parse and Use Secrets
      run: |
        echo $SECRET_JSON | jq -r '.dbUsername'
        echo $SECRET_JSON | jq -r '.dbPassword'
        echo $SECRET_JSON | jq -r '.apiKey'
      env:
        SECRET_JSON: ${{ steps.fetch-secret.outputs.secret }}
